In [1]:
import pandas as pd

In [3]:
air_df = pd.read_csv("AirQuality.csv")
heart_df = pd.read_csv("heart.csv")

In [5]:
# Inspect nulls and data types
air_df.info()
heart_df.info()

# Fill missing values
air_df.fillna(air_df.mean(numeric_only=True), inplace=True)
heart_df.fillna(heart_df.mean(numeric_only=True), inplace=True)

# Remove duplicates
air_df.drop_duplicates(inplace=True)
heart_df.drop_duplicates(inplace=True)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   object
 3   PT08.S1(CO)    9357 non-null   int64 
 4   NMHC(GT)       9357 non-null   int64 
 5   C6H6(GT)       9357 non-null   object
 6   PT08.S2(NMHC)  9357 non-null   int64 
 7   NOx(GT)        9357 non-null   int64 
 8   PT08.S3(NOx)   9357 non-null   int64 
 9   NO2(GT)        9357 non-null   int64 
 10  PT08.S4(NO2)   9357 non-null   int64 
 11  PT08.S5(O3)    9357 non-null   int64 
 12  T              9357 non-null   object
 13  RH             9357 non-null   object
 14  AH             9357 non-null   object
dtypes: int64(8), object(7)
memory usage: 1.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Co

In [9]:
# Merge on common keys (location and date)
#combined_df = pd.merge(air_df, heart_df, on=["location", "date"], how="inner")
# Reset index and concatenate
combined_df = pd.concat([air_df.reset_index(drop=True), heart_df.reset_index(drop=True)], axis=1)
combined_df

Date      Time CO(GT)  PT08.S1(CO)  NMHC(GT) C6H6(GT)  \
0     10/03/2004  18.00.00    2,6         1360       150     11,9   
1     10/03/2004  19.00.00      2         1292       112      9,4   
2     10/03/2004  20.00.00    2,2         1402        88      9,0   
3     10/03/2004  21.00.00    2,2         1376        80      9,2   
4     10/03/2004  22.00.00    1,6         1272        51      6,5   
...          ...       ...    ...          ...       ...      ...   
9352  04/04/2005  10.00.00    3,1         1314      -200     13,5   
9353  04/04/2005  11.00.00    2,4         1163      -200     11,4   
9354  04/04/2005  12.00.00    2,4         1142      -200     12,4   
9355  04/04/2005  13.00.00    2,1         1003      -200      9,5   
9356  04/04/2005  14.00.00    2,2         1071      -200     11,9   

      PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  ...   chol  fbs restecg  \
0              1046      166          1056      113  ...  233.0  1.0     0.0   
1               955      103          1174       92  ...  250.0  0.0     1.0   
2               939      131          1140      114  ...  204.0  0.0     0.0   
3               948      172          1092      122  ...  236.0  0.0     1.0   
4               836      131          1205      116  ...  354.0  0.0     1.0   
...             ...      ...           ...      ...  ...    ...  ...     ...   
9352           1101      472           539      190  ...    NaN  NaN     NaN   
9353           1027      353           604      179  ...    NaN  NaN     NaN   
9354           1063      293           603      175  ...    NaN  NaN     NaN   
9355            961      235           702      156  ...    NaN  NaN     NaN   
9356           1047      265           654      168  ...    NaN  NaN     NaN   

     thalachh exng  oldpeak  slp  caa  thall  output  
0       150.0  0.0      2.3  0.0  0.0    1.0     1.0  
1       187.0  0.0      3.5  0.0  0.0    2.0     1.0  
2       172.0  0.0      1.4  2.0  0.0    2.0     1.0  
3       178.0  0.0      0.8  2.0  0.0    2.0     1.0  
4       163.0  1.0      0.6  2.0  0.0    2.0     1.0  
...       ...  ...      ...  ...  ...    ...     ...  
9352      NaN  NaN      NaN  NaN  NaN    NaN     NaN  
9353      NaN  NaN      NaN  NaN  NaN    NaN     NaN  
9354      NaN  NaN      NaN  NaN  NaN    NaN     NaN  
9355      NaN  NaN      NaN  NaN  NaN    NaN     NaN  
9356      NaN  NaN      NaN  NaN  NaN    NaN     NaN  

[9357 rows x 29 columns]

In [11]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Encode categorical variables
for col in combined_df.select_dtypes(include='object').columns:
    combined_df[col] = LabelEncoder().fit_transform(combined_df[col])

# Normalize or scale numerical features
scaler = StandardScaler()
combined_df[combined_df.columns] = scaler.fit_transform(combined_df)


In [13]:
combined_df

Date      Time    CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0    -0.720254  0.939133  0.631982     0.942983  2.211236 -1.098203   
1    -0.720254  1.083583  0.254807     0.736807  1.939383  1.409175   
2    -0.720254  1.228033  0.416453     1.070327  1.767687  1.381546   
3    -0.720254  1.372483  0.416453     0.991495  1.710454  1.395361   
4    -0.720254  1.516933 -0.176250     0.676167  1.502988  1.201954   
...        ...       ...       ...          ...       ...       ...   
9352 -1.349242 -0.216467  0.955274     0.803511 -0.292670 -0.987685   
9353 -1.349242 -0.072017  0.524218     0.345678 -0.292670 -1.132740   
9354 -1.349242  0.072433  0.524218     0.282006 -0.292670 -1.063666   
9355 -1.349242  0.216883  0.362571    -0.139442 -0.292670  1.416083   
9356 -1.349242  0.361333  0.416453     0.066734 -0.292670 -1.098203   

      PT08.S2(NMHC)   NOx(GT)  PT08.S3(NOx)   NO2(GT)  ...      chol  \
0          0.442297 -0.010166      0.810649  0.432124  ... -0.261285   
1          0.176459 -0.254902      1.177136  0.266684  ...  0.067741   
2          0.129719 -0.146131      1.071538  0.440002  ... -0.822564   
3          0.156010  0.013142      0.922459  0.503027  ... -0.203222   
4         -0.171174 -0.146131      1.273416  0.455759  ...  2.080602   
...             ...       ...           ...       ...  ...       ...   
9352       0.602967  1.178552     -0.795059  1.038740  ...       NaN   
9353       0.386792  0.716273     -0.593181  0.952081  ...       NaN   
9354       0.491958  0.483191     -0.596287  0.920568  ...       NaN   
9355       0.193987  0.257878     -0.288811  0.770884  ...       NaN   
9356       0.445218  0.374419     -0.437890  0.865421  ...       NaN   

           fbs   restecg  thalachh      exng   oldpeak       slp       caa  \
0     2.389793 -1.002541  0.018826 -0.698344  1.084022 -2.271182 -0.714911   
1    -0.418446  0.901657  1.636979 -0.698344  2.118926 -2.271182 -0.714911   
2    -0.418446 -1.002541  0.980971 -0.698344  0.307844  0.979514 -0.714911   
3    -0.418446  0.901657  1.243374 -0.698344 -0.209608  0.979514 -0.714911   
4    -0.418446  0.901657  0.587366  1.431958 -0.382092  0.979514 -0.714911   
...        ...       ...       ...       ...       ...       ...       ...   
9352       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9353       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9354       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9355       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
9356       NaN       NaN       NaN       NaN       NaN       NaN       NaN   

         thall    output  
0    -2.147955  0.917313  
1    -0.513994  0.917313  
2    -0.513994  0.917313  
3    -0.513994  0.917313  
4    -0.513994  0.917313  
...        ...       ...  
9352       NaN       NaN  
9353       NaN       NaN  
9354       NaN       NaN  
9355       NaN       NaN  
9356       NaN       NaN  

[9357 rows x 29 columns]

In [15]:
# Clip outliers based on IQR
Q1 = combined_df.quantile(0.25)
Q3 = combined_df.quantile(0.75)
IQR = Q3 - Q1
combined_df = combined_df[~((combined_df < (Q1 - 1.5 * IQR)) | (combined_df > (Q3 + 1.5 * IQR))).any(axis=1)]

In [23]:
# Drop rows with missing target
heart_df.dropna(subset=['output'], inplace=True)

# Feature/target split
X_heart = heart_df.drop(columns='output')
y_heart = heart_df['output']

# Scale features
X_heart = StandardScaler().fit_transform(X_heart)

# Train/test split
Xh_train, Xh_test, yh_train, yh_test = train_test_split(X_heart, y_heart, test_size=0.2, random_state=42)

# Train model
heart_model = RandomForestClassifier(random_state=42)
heart_model.fit(Xh_train, yh_train)

print("❤️ Heart Disease Model Accuracy:", accuracy_score(yh_test, heart_model.predict(Xh_test)))


❤️ Heart Disease Model Accuracy: 0.8688524590163934


In [27]:
air_df['CO(GT)'] = pd.to_numeric(air_df['CO(GT)'], errors='coerce')


In [41]:
import numpy as np
# Replace invalid placeholder values with NaN
air_df['CO(GT)'] = pd.to_numeric(air_df['CO(GT)'], errors='coerce')
air_df['CO(GT)'] = air_df['CO(GT)'].replace(-200.0, np.nan)

# Drop NaNs after cleaning
air_df = air_df.dropna(subset=['CO(GT)'])

# Create pollution level categories (low/med/high)
air_df['pollution_level'] = pd.cut(
    air_df['CO(GT)'],
    bins=3,
    labels=[0, 1, 2],
    #duplicates='drop'  # Handles duplicate edges gracefully
)

In [57]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Convert all string columns with commas to proper float format
for col in air_df.columns:
    if air_df[col].dtype == 'object':
        # Replace ',' with '.' and convert to float where applicable
        air_df[col] = air_df[col].str.replace(',', '.').astype(float, errors='ignore')

# Drop original target and non-numeric fields
X_air = air_df.drop(columns=['pollution_level', 'Date', 'Time'], errors='ignore')
y_air = air_df['pollution_level'].astype(int)

# Fill remaining NaNs and scale
X_air = X_air.fillna(X_air.mean(numeric_only=True))
X_air = StandardScaler().fit_transform(X_air)

if 'CO(GT)' in air_df.columns:
    air_df = air_df.drop(columns=['CO(GT)'])

# Train/test split
Xa_train, Xa_test, ya_train, ya_test = train_test_split(X_air, y_air, test_size=0.2, stratify=y_air, random_state=42)

# Train model
air_model = RandomForestClassifier(random_state=42, class_weight='balanced')
air_model.fit(Xa_train, ya_train)

# Evaluate model
accuracy = accuracy_score(ya_test, air_model.predict(Xa_test))
print("🌫️ Air Quality Model Accuracy:", accuracy)


🌫️ Air Quality Model Accuracy: 0.963302752293578


In [51]:
print("Class distribution in y_air:\n", y_air.value_counts(normalize=True))


Class distribution in y_air:
 pollution_level
0    0.822018
1    0.157798
2    0.020183
Name: proportion, dtype: float64


In [59]:
from sklearn.metrics import classification_report, confusion_matrix
#AIRQUALITY
y_pred = air_model.predict(Xa_test)

print("📋 Classification Report:\n", classification_report(ya_test, y_pred))
print("🧮 Confusion Matrix:\n", confusion_matrix(ya_test, y_pred))


📋 Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.99      0.98        90
           1       0.93      0.82      0.88        17
           2       1.00      1.00      1.00         2

    accuracy                           0.96       109
   macro avg       0.97      0.94      0.95       109
weighted avg       0.96      0.96      0.96       109

🧮 Confusion Matrix:
 [[89  1  0]
 [ 3 14  0]
 [ 0  0  2]]


In [65]:

# Make predictions
y_pred_heart = heart_model.predict(Xh_test)

# Classification report
print("\n📋 Classification Report:\n", classification_report(yh_test, y_pred_heart))

# Confusion matrix
print("🧮 Confusion Matrix:\n", confusion_matrix(yh_test, y_pred_heart))



📋 Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.90      0.87        29
           1       0.90      0.84      0.87        32

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61

🧮 Confusion Matrix:
 [[26  3]
 [ 5 27]]
